//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentACar.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Linq;
    using System.IO;
    using System.Web.Mvc;
    using System.Web.Hosting;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public override int SaveChanges()
        {
            //var vehicles = ChangeTracker.Entries().Where(e => e.Entity is Vehicle && e.State == EntityState.Deleted);
            var vehicles = ChangeTracker.Entries().Where(e => e.Entity is Vehicle && e.State == EntityState.Deleted).ToList();
            var vehiclesCasted = vehicles.Select(v => v.Entity as Vehicle).ToList();

            foreach (var vehicle in vehiclesCasted)
            {
                var images = this.VehicleImages.Where(vi => vi.VehicleId == vehicle.Id).Select(vi => vi.Image).ToList();
                foreach (var image in images)
                {
                    var rootPath = HostingEnvironment.MapPath(ApplicationWideData.StorageRootPath);
                    var currentImagePath = Path.Combine(rootPath, image.Path);
                    if (File.Exists(currentImagePath))
                    {
                        File.Delete(currentImagePath);
                    }
                }
            }


            return base.SaveChanges();
        }

        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Booking> Bookings { get; set; }
        public virtual DbSet<BookingRequest> BookingRequests { get; set; }
        public virtual DbSet<GlobalData> GlobalDatas { get; set; }
        public virtual DbSet<Image> Images { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<PaymentMethod> PaymentMethods { get; set; }
        public virtual DbSet<RequestStatu> RequestStatus { get; set; }
        public virtual DbSet<Sublocation> Sublocations { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Vehicle> Vehicles { get; set; }
        public virtual DbSet<VehicleCategory> VehicleCategories { get; set; }
        public virtual DbSet<VehicleImage> VehicleImages { get; set; }
        public virtual DbSet<VehicleLocation> VehicleLocations { get; set; }
        public virtual DbSet<VehicleTransmission> VehicleTransmissions { get; set; }
        public virtual DbSet<VisitorQuery> VisitorQueries { get; set; }
    }
}
