//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentACar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehicle()
        {
            this.BookingRequests = new HashSet<BookingRequest>();
            this.VehicleImages = new HashSet<VehicleImage>();
            this.VehicleLocations = new HashSet<VehicleLocation>();
        }
    
        public int Id { get; set; }
        public int CategoryId { get; set; }
        public decimal Fare1 { get; set; }
        public decimal Fare2 { get; set; }
        public decimal Fare3 { get; set; }
        public string Title { get; set; }
        public string Make { get; set; }
        public int Year { get; set; }
        public int TransmissionId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingRequest> BookingRequests { get; set; }
        public virtual VehicleCategory VehicleCategory { get; set; }
        public virtual VehicleTransmission VehicleTransmission { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehicleImage> VehicleImages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehicleLocation> VehicleLocations { get; set; }
    }
}
